#!/bin/bash
# run this to create a new branch locally and on the remote
if [ $# -ne 1 ]; then
	echo "please provide the name for the new branch"
	exit 1
fi
branch=$1
git checkout -b $branch
git push -u origin $branch
